In [1]:
import pandas as pd
from pycaret.classification import *

In [2]:
training_data = pd.read_csv('train_data.csv')
testing_data = pd.read_csv('test_data.csv')
training_data = training_data.iloc[:, 1:]
training_data.describe()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29,f30,f31,f32,f33,f34,f35,f36,f37,f38,f39,f40,f41,f42,f43,f44,f45,f46,f47,f48,f49,f50,target
count,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.00000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000,23999.000000
mean,0.468707,0.457409,0.482216,0.445491,0.510032,0.484932,0.525397,0.558937,0.515624,0.468441,0.517923,0.497197,0.490387,0.506212,0.541206,0.457601,0.518949,0.477750,0.538946,0.482690,0.522320,0.541080,0.532704,0.454908,0.503339,0.495131,0.566798,0.481167,0.46372,0.513373,0.494756,0.485472,0.526102,0.460180,0.482819,0.533824,0.520465,0.513100,0.498100,0.476983,0.528105,0.495641,0.484383,0.490314,0.531846,0.530936,0.519071,0.519765,0.493850,0.521915,0.493729
std,0.133171,0.097082,0.114720,0.110729,0.112435,0.116867,0.119023,0.113811,0.102985,0.118092,0.103662,0.100134,0.115041,0.146520,0.124689,0.097306,0.115563,0.129459,0.118560,0.093214,0.141276,0.118542,0.095472,0.093405,0.112400,0.092913,0.097026,0.113013,0.11604,0.113909,0.130677,0.111674,0.122142,0.113073,0.124446,0.094981,0.117929,0.115106,0.114503,0.112757,0.124216,0.124894,0.120486,0.133060,0.114075,0.108027,0.111077,0.114019,0.110060,0.105324,0.499971
min,0.020040,0.073640,0.096520,0.054510,0.059410,0.000000,0.052570,0.079370,0.076370,0.061270,0.094480,0.091690,0.050590,0.030080,0.065420,0.092480,0.060290,0.001550,0.141660,0.034190,0.053260,0.081170,0.121450,0.076030,0.072970,0.115360,0.161050,0.135690,0.07312,0.074470,0.038980,0.071290,0.109300,0.032800,0.006900,0.157420,0.129490,0.090690,0.080580,0.096310,0.000000,0.050850,0.091590,0.060580,0.056880,0.136660,0.057030,0.094740,0.068990,0.122710,0.000000
25%,0.375055,0.391935,0.402850,0.370665,0.436440,0.403875,0.447050,0.483775,0.447340,0.386245,0.450360,0.430770,0.412045,0.400545,0.456300,0.393320,0.437680,0.387430,0.456295,0.420170,0.424840,0.461450,0.469120,0.392440,0.431895,0.434210,0.501925,0.399630,0.38476,0.436165,0.401635,0.411070,0.441415,0.382855,0.396005,0.471175,0.439515,0.435025,0.420020,0.399460,0.442395,0.411330,0.398540,0.400265,0.456380,0.454440,0.444035,0.442030,0.420720,0.450955,0.000000
50%,0.468620,0.457510,0.479780,0.445100,0.513870,0.484950,0.530030,0.563900,0.516700,0.462160,0.520910,0.497610,0.490640,0.504660,0.545040,0.457270,0.514090,0.478580,0.537760,0.482080,0.526430,0.542680,0.532400,0.453040,0.508870,0.495970,0.569170,0.478520,0.45520,0.515730,0.493100,0.488570,0.527360,0.461870,0.482880,0.534840,0.517360,0.511220,0.498180,0.473330,0.527960,0.495580,0.479940,0.486380,0.534010,0.528460,0.519590,0.517820,0.495810,0.524000,0.000000
75%,0.561385,0.522230,0.557325,0.519295,0.587645,0.564600,0.609000,0.638190,0.583735,0.544240,0.588080,0.563465,0.566710,0.610095,0.629470,0.521160,0.595930,0.570060,0.621025,0.545405,0.621050,0.623735,0.596440,0.516595,0.580005,0.557925,0.632205,0.556810,0.53348,0.592415,0.586355,0.560980,0.612400,0.537900,0.568310,0.597175,0.599905,0.591450,0.577630,0.551380,0.612200,0.579190,0.565435,0.576975,0.610405,0.604565,0.594645,0.597925,0.569325,0.593640,1.000000
max,0.969750,1.000000,0.908310,0.931690,0.969410,0.971560,0.916970,0.969910,0.954220,0.953200,0.912790,1.000000,0.958230,0.965980,0.955930,0.904050,0.952330,0.926530,0.991440,0.852860,0.950510,0.957590,0.963080,0.868940,0.883420,0.984300,0.922300,0.900170,0.93938,0.947210,0.942460,0.959720,0.943370,0.885980,0.988760,0.894060,0.948210,0.976800,0.917820,1.000000,0.992380,0.933910,0.911920,0.951230,0.957970,0.901580,0.960350,0.919870,0.865960,0.963560,1.000000

In [3]:
s = setup(data = training_data, target='target',  remove_outliers=True , normalize=True, silent=True)
# transformation=True for lr
# remove_outliers = True, outliers_threshold = 0.05

In [4]:
models()

[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
[LightGBM] [Fatal] CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1

,Name,Reference,Turbo
ID,,,
lr,Logistic Regression,sklearn.linear_model._logistic.LogisticRegression,True
knn,K Neighbors Classifier,sklearn.neighbors._classification.KNeighborsCl...,True
nb,Naive Bayes,sklearn.naive_bayes.GaussianNB,True
dt,Decision Tree Classifier,sklearn.tree._classes.DecisionTreeClassifier,True
svm,SVM - Linear Kernel,sklearn.linear_model._stochastic_gradient.SGDC...,True
rbfsvm,SVM - Radial Kernel,sklearn.svm._classes.SVC,False
gpc,Gaussian Process Classifier,sklearn.gaussian_process._gpc.GaussianProcessC...,False
mlp,MLP Classifier,sklearn.neural_network._multilayer_perceptron....,False
ridge,Ridge Classifier,sklearn.linear_model._ridge.RidgeClassifier,True
rf,Random Forest Classifier,sklearn.ensemble._forest.RandomForestClassifier,True
qda,Quadratic Discriminant Analysis,sklearn.discriminant_analysis.QuadraticDiscrim...,True
ada,Ada Boost Classifier,sklearn.ensemble._weight_boosting.AdaBoostClas...,True
gbc,Gradient Boosting Classifier,sklearn.ensemble._gb.GradientBoostingClassifier,True
lda,Linear Discriminant Analysis,sklearn.discriminant_analysis.LinearDiscrimina...,True
et,Extra Trees Classifier,sklearn.ensemble._forest.ExtraTreesClassifier,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMClassifier,True
dummy,Dummy Classifier,sklearn.dummy.DummyClassifier,True

In [4]:
cm = compare_models(include=['lr','qda','nb','lda'])

In [5]:
top3 = compare_models(n_select = 3)

In [6]:
qdaModel = create_model('qda', fold=10)

In [10]:
lrModel_nofold = create_model('lr')

In [9]:
qdaModel_tuned_100itr = tune_model(qdaModel, n_iter=100 ,choose_better=True)

In [8]:
qdaModel_tuned = tune_model(qdaModel, choose_better=True)

In [10]:
qdaModel_tuned_optimize = tune_model(qdaModel, n_iter=100, search_library='scikit-optimize', choose_better=True)

In [11]:
qdaModel_tuned_tune = tune_model(qdaModel, n_iter=100, search_library='tune-sklearn', choose_better=True)

In [14]:
lrModel_tuned_optuna = tune_model(lrModel, n_iter=100, search_library='optuna', choose_better=True)

In [12]:
qdaModel_tuned_optimize_ensemble_bagging = ensemble_model(qdaModel_tuned_optimize,method='Bagging', choose_better=True)

In [14]:
qdaModel_tuned_optimize_ensemble_boosting = ensemble_model(qdaModel_tuned_optimize,method='Boosting', choose_better=True)

TypeError: Estimator not supported for the Boosting method. Change the estimator or method to 'Bagging'.

In [15]:
blender = blend_models(top3)

In [16]:
stacker = stack_models(top3)

In [17]:
save_model(qdaModel_tuned_optimize, 'qdaModel_tuned_optimize05453')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=False, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[], target='target',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_stra...
                 ('dummy', Dummify(target='target')),
                 ('fix_perfect', Remove_100(target='target')),
                 ('clean_names', Clean_Colum_Names()),
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough'),
                 ['trained_model',
                  QuadraticDiscriminantAnalysis(priors=None,
                                                reg_param=0.05437517067095166,
                                                store_covariance=False,
                                                tol=0.0001)]],
          verbose=False),
 'qdaModel_tuned_optimize05453.pkl')

In [18]:
final_qda = finalize_model(qdaModel_tuned_optimize)

In [19]:
save_model(final_qda, 'final_qdaModel_tuned_optimize05453')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=False, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[], target='target',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_stra...
                 ('dummy', Dummify(target='target')),
                 ('fix_perfect', Remove_100(target='target')),
                 ('clean_names', Clean_Colum_Names()),
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough'),
                 ['trained_model',
                  QuadraticDiscriminantAnalysis(priors=None,
                                                reg_param=0.05437517067095166,
                                                store_covariance=False,
                                                tol=0.0001)]],
          verbose=False),
 'final_qdaModel_tuned_optimize05453.pkl')

In [20]:
pred = predict_model(final_qda, data=testing_data)

In [21]:
pred

,id,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f43,f44,f45,f46,f47,f48,f49,f50,Label,Score
0,nc3dea071da1944b,0.24847,0.55312,0.70589,0.71547,0.44433,0.34094,0.39226,0.48390,0.44880,...,0.23107,0.32082,0.58618,0.39162,0.58575,0.49389,0.34608,0.60458,0,0.5148
1,n22d95133dce7449,0.35610,0.50317,0.56731,0.58409,0.34255,0.38761,0.55026,0.59748,0.49126,...,0.53355,0.46335,0.49657,0.44691,0.60637,0.49626,0.42141,0.48827,0,0.5265
2,ndb9c52980cd9476,0.26545,0.63635,0.62526,0.36129,0.47972,0.43528,0.53891,0.68595,0.46213,...,0.28314,0.24980,0.53049,0.54310,0.38520,0.52152,0.70290,0.42735,1,0.5632
3,na13ca2a8d090425,0.41565,0.40977,0.59554,0.51657,0.41246,0.36535,0.48067,0.62167,0.56247,...,0.39664,0.33040,0.62151,0.34951,0.50230,0.52614,0.52327,0.39415,1,0.6453
4,nb9b008749ee643a,0.30859,0.53767,0.37151,0.25692,0.23348,0.45774,0.45095,0.40326,0.49709,...,0.65674,0.66758,0.37675,0.70034,0.56275,0.67308,0.49376,0.39979,0,0.5196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22358,n217d6293192b46f,0.68764,0.42877,0.62459,0.39127,0.56343,0.52240,0.56785,0.75272,0.40546,...,0.44702,0.40822,0.56956,0.54087,0.64767,0.61174,0.59401,0.46431,0,0.6489
22359,nec97a96bcc3a449,0.50059,0.54289,0.52768,0.49786,0.47081,0.45701,0.52251,0.65912,0.44007,...,0.47997,0.40386,0.67543,0.59592,0.50695,0.43193,0.48888,0.57359,0,0.5422
22360,n1ed0070ef666435,0.50869,0.44358,0.30611,0.52404,0.71491,0.45710,0.75289,0.64944,0.47056,...,0.38436,0.46426,0.50507,0.32266,0.76017,0.56673,0.50958,0.49367,0,0.5205
22361,ndb741f3bddcc4c6,0.46006,0.68691,0.67320,0.28909,0.24250,0.49745,0.15369,0.49682,0.43445,...,0.47252,0.46381,0.73513,0.48209,0.49414,0.39796,0.38565,0.49893,1,0.5986
22362,n8cbe55db4a67481,0.42337,0.49390,0.40428,0.37485,0.53176,0.45052,0.69015,0.52926,0.42719,...,0.48880,0.60468,0.52557,0.56237,0.46001,0.58134,0.49721,0.62812,0,0.5464

In [22]:
pred = pred.rename(columns = {'id':'id', 'Label':'target'})
pred['target'] = pred['target'].astype(int)
pred_new = pd.concat([pred['id'], pred['target']], axis = 1)
pred_new

                     id  target
0      nc3dea071da1944b       0
1      n22d95133dce7449       0
2      ndb9c52980cd9476       1
3      na13ca2a8d090425       1
4      nb9b008749ee643a       0
...                 ...     ...
22358  n217d6293192b46f       0
22359  nec97a96bcc3a449       0
22360  n1ed0070ef666435       0
22361  ndb741f3bddcc4c6       1
22362  n8cbe55db4a67481       0

[22363 rows x 2 columns]

In [23]:
pred_new.to_csv('testing_qdamodel_tuned.csv', index=False)